// Generated by ReScript, PLEASE EDIT WITH CARE


var buttonStyle = "absolute p-4 w-20 h-20 flex justify-center items-center bg-white rounded-full border-8 cursor-pointer hover:scale-105";

export {
  buttonStyle ,
}
/* No side effect */
