// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "ROCK"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "PAPER"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "SCISSORS"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "LIZARD"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "SPOCK"
                            })
                      ],
                      className: "text-white -space-y-3 text-lg"
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "Score",
                              className: "text-score-text"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "01",
                              className: "text-6xl text-dark-text"
                            })
                      ],
                      className: "flex flex-col items-center bg-white py-3 px-10 rounded-xl"
                    })
              ],
              className: "flex justify-between items-center p-4 border-header-outline border-4 rounded-3xl"
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
