// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var list_of_hand = [
  "lizard",
  "rock",
  "paper",
  "scissor",
  "spock"
];

var randomize = Math.floor(list_of_hand.length * Math.random());

var housePick = list_of_hand[randomize];

function setColorHouse(x) {
  switch (x) {
    case 0 :
        return "border-lizard";
    case 1 :
        return "border-rock";
    case 2 :
        return "border-paper";
    case 3 :
        return "border-scissor";
    case 4 :
        return "border-spock";
    default:
      return "border-0";
  }
}

function setColor(x) {
  switch (x) {
    case "lizard" :
        return "border-lizard";
    case "paper" :
        return "border-paper";
    case "rock" :
        return "border-rock";
    case "scissor" :
        return "border-scissor";
    case "spock" :
        return "border-spock";
    default:
      return "border-0";
  }
}

function GameModal(props) {
  var pick = props.pick;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("section", {
                              children: JsxRuntime.jsx("img", {
                                    src: "/icon-" + pick + ".svg"
                                  }),
                              className: "" + setColor(pick) + " p-4 w-40 h-40 flex justify-center items-center bg-white rounded-full border-[16px] cursor-pointer hover:scale-110 trasnsition-all duration-300 ease-in-out"
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "YOU PICKED",
                              className: "text-white text-2xl"
                            })
                      ],
                      className: "flex flex-col items-center gap-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("section", {
                              children: JsxRuntime.jsx("img", {
                                    src: "/icon-" + housePick + ".svg"
                                  }),
                              className: "" + setColorHouse(randomize) + " p-4 w-40 h-40 flex justify-center items-center bg-white rounded-full border-[16px] cursor-pointer hover:scale-110 trasnsition-all duration-300 ease-in-out"
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "THE HOUSE PICKED",
                              className: "text-white text-2xl"
                            })
                      ],
                      className: "flex flex-col items-center gap-4"
                    })
              ],
              className: "grid grid-cols-2 my-10",
              id: "game"
            });
}

var make = GameModal;

export {
  list_of_hand ,
  randomize ,
  housePick ,
  setColorHouse ,
  setColor ,
  make ,
}
/* randomize Not a pure module */
