// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Layout from "./Layout.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(Layout.make, {
              children: "Hello"
            });
}

var make = App;

export {
  make ,
}
/* Layout Not a pure module */
