// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rule from "./Components/Modal/Rule.bs.mjs";
import * as React from "react";
import * as Header from "./Components/Header/Header.bs.mjs";
import * as RuleState from "./Components/State/RuleState.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Layout(props) {
  var match = React.useState(function () {
        return 0;
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {
                      score: match[0]
                    }),
                JsxRuntime.jsx("section", {
                      children: props.children
                    }),
                JsxRuntime.jsx(RuleState.Provider.make, {
                      children: JsxRuntime.jsx(Rule.make, {})
                    })
              ],
              className: "p-10 relative flex flex-col gap-10 justify-center"
            });
}

var make = Layout;

export {
  make ,
}
/* Rule Not a pure module */
