// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as RuleState from "../State/RuleState.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Rule(props) {
  var match = Curry._1(RuleState.Context.use, undefined);
  var dispatch = match[1];
  var state = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("section", {
                              children: JsxRuntime.jsx("h1", {
                                    children: "RULES",
                                    className: "text-dark-text text-xl"
                                  }),
                              className: "flex justify-between items-center"
                            }),
                        JsxRuntime.jsx("section", {
                              children: JsxRuntime.jsx("img", {
                                    src: "/image-rules-bonus.svg"
                                  }),
                              className: "flex justify-center items-center"
                            }),
                        state === /* DisplayRule */0 ? JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx("img", {
                                      src: "/icon-close.svg"
                                    }),
                                className: "text-dark-text text-xl cursor-pointer",
                                onClick: (function (param) {
                                    Curry._1(dispatch, /* Toggle */0);
                                  })
                              }) : JsxRuntime.jsx(JsxRuntime.Fragment, {})
                      ],
                      className: "fixed z-50 bg-white py-20 px-10 top-0 left-0 w-screen h-screen flex flex-col justify-between items-center " + (
                        state === /* HideRule */1 ? "hidden" : ""
                      ) + "",
                      id: "rules"
                    }),
                JsxRuntime.jsx("div", {
                      children: "RULES",
                      className: "inline-block border-header-outline border-4 py-2 px-10 rounded-xl text-white hover:bg-white hover:text-dark-text cursor-pointer",
                      onClick: (function (param) {
                          Curry._1(dispatch, /* Toggle */0);
                        })
                    })
              ],
              className: "flex flex-col items-center lg:items-end"
            });
}

var make = Rule;

export {
  make ,
}
/* RuleState Not a pure module */
